services:
  app:
    restart: unless-stopped
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      PHP_MEMORY_LIMIT: 512M
    networks:
      - firebase-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - firebase-network

networks:
  firebase-network:
    driver: bridge